- platform: pilight
  name: rf_motion_flur
  device_class: motion
  variable: 'state'
  payload:
    protocol: 'arctech_switch'
    id: 21633024
    unit: 1
  payload_on: 'on'
  disarm_after_trigger: true
