- alias: ez_nightlight_on
  trigger:
    platform: sun
    event: sunset
    offset: '01:00:00'
  condition:
    - condition: state
      entity_id: group.familie
      state: 'home'
  action:
    - service: script.gateway_nightlight_on

- alias: ez_nightlight_off
  trigger:
    platform: sun
    event: sunrise
    offset: '01:00:00'
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_286c0788a9dd

- alias: ez_auto_off
  trigger:
    platform: time
    hours: '/1'
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.beleuchtung_esszimmer
        state: 'on'
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d0001e562ad
        state: 'off'
        for:
          minutes: 15
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d00012326f7
        state: 'off'
        for:
          minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: switch.beleuchtung_esszimmer
