homeassistant:
  name: Zuhause
  latitude: !secret HOMEASSISTANT_LATITUDE
  longitude: !secret HOMEASSISTANT_LONGITUDE
  elevation: 350
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob:
    'switch.rf_*':
      assumed_state: false
      initial_state: false
      icon: 'mdi:lightbulb'
    'sensor.temperature_*':
      friendly_name: Temperatur
    'sensor.pressure_*':
      friendly_name: Luftdruck
    'sensor.humidity_*':
      friendly_name: Luftfeuchtigkeit
http:
  api_password: !secret HTTP_API_PASSWORD
  trusted_networks:
    - 192.168.10.0/24

cloud:
  alexa:
    filter:
      include_domains:
        - light
        - media_player
        - scene
        - script
        - switch
      exclude_entities:
        - switch.example
    entity_config:
      light.kitchen:
        name: Custom Name for Alexa
      switch.stairs:
        display_categories: LIGHT
      switch.volumio_kueche:
        name: Radio Küche
      media_player.lg_tv:
        name: TV
        display_categories: TV

config:
history:
homekit:
ios:
logbook:
map:
sun:
updater:

frontend:
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom_ui/custom-weather-card.html
  extra_html_url_es5:
    - /local/custom_ui/custom-weather-card.html

discovery:
  ignore:
    - panasonic_viera

tts:
  - platform: google

tado:
  username: !secret TADO_USERNAME
  password: !secret TADO_PASSWORD

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: 192.168.10.95
  port: 1883
  client_id: homeassistant
  protocol: 3.1
  username: !secret MQTT_USERNAME
  password: !secret MQTT_PASSWORD

camera:
  - platform: ffmpeg
    name: arthur_cam
    input: -rtsp_transport tcp -i rtsp://192.168.10.76/unicast
    extra_arguments: '-c:v h264_omx'

pilight:
  host: 192.168.10.93
  port: 5000
  send_delay: 0.8

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret XIAOMI_GATEWAY_MAC
      key: !secret XIAOMI_GATEWAY_KEY

notify:
  - name: slack
    platform: slack
    api_key: !secret SLACK_API_KEY
    default_channel: 'automation'

panel_iframe:
 nodered:
   title: 'Node-RED'
   icon: 'mdi:shuffle-variant'
   url: 'http://192.168.10.95:1880/'

weather:
  - platform: yweather

automation: !include_dir_merge_list automations
binary_sensor: !include_dir_merge_list binary_sensor
device_tracker: !include_dir_merge_list device_tracker
group: !include_dir_merge_named groups
input_boolean: !include inputs/boolean.yaml
input_datetime: !include inputs/datetime.yaml
input_text: !include inputs/text.yaml
light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_player
scene: !include_dir_merge_list scene
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch

