homeassistant:
  name: Zuhause
  latitude: !secret HOMEASSISTANT_LATITUDE
  longitude: !secret HOMEASSISTANT_LONGITUDE
  elevation: 350
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob:
    'switch.rf_*':
      assumed_state: false
      icon: 'mdi:lightbulb'
    'sensor.temperature_*':
      friendly_name: Temperatur
    'sensor.pressure_*':
      friendly_name: Luftdruck
    'sensor.humidity_*':
      friendly_name: Luftfeuchtigkeit
  whitelist_external_dirs:
    - '/tmp'
  auth_providers:
     - type: homeassistant
     - type: trusted_networks

http:
  trusted_networks:
    - 127.0.0.1
    - 192.168.10.0/24
    - 192.168.20.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

downloader:
  download_dir: 'www/downloads'

ffmpeg:
  ffmpeg_bin: /usr/local/bin/ffmpeg

custom_updater:

config:
history:
logbook:
map:
sun:
updater:
wake_on_lan:

ring:
  username: !secret RING_USERNAME
  password: !secret RING_PASSWORD

# recorder:
#   purge_keep_days: 7
#   db_url: mysql://homeassistant@192.168.10.95/homeassistant?charset=utf8
#   exclude:
#     domains:
#       - automation
#       - updater
#     entities:
#       - sun.sun # Don't record sun data
#       - sensor.last_boot # Comes from 'systemmonitor' sensor platform
#       - sensor.date

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google
    language: 'de'

tado:
  username: !secret TADO_USERNAME
  password: !secret TADO_PASSWORD

mqtt:
  # discovery: true
  # discovery_prefix: homeassistant
  broker: 192.168.10.150
  port: 1883
  client_id: !secret MQTT_CLIENT_ID
  username: !secret MQTT_USERNAME
  password: !secret MQTT_PASSWORD

camera:
  - platform: ffmpeg
    name: arthur_cam
    input: -rtsp_transport tcp -i rtsp://192.168.20.62/unicast
  # - platform: mjpeg
  #   name: arthur_cam_mjpeg
  #   mjpeg_url: rtsp://192.168.20.62/unicast
    #extra_arguments: '-c:v h264_omx'
  # - platform: ffmpeg
  #   name: camera_hof
  #   input: -rtsp_transport tcp -i rtsp://192.168.10.115/unicast
  # - platform: ring
  #   name: ring
  #   ffmpeg_arguments: -pred 1 -q:v 2
  # - platform: mjpeg
  #   name: camera_hof
  #   mjpeg_url: rtsp://192.168.10.115/unicast
    #extra_arguments: '-c:v h264_omx'

pilight:
  host: 192.168.10.93
  port: 5000
  send_delay: 0.8

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret XIAOMI_GATEWAY_1_MAC
      key: !secret XIAOMI_GATEWAY_1_KEY
    - mac: !secret XIAOMI_GATEWAY_2_MAC
      key: !secret XIAOMI_GATEWAY_2_KEY

notify:
  - name: slack
    platform: slack
    api_key: !secret SLACK_API_KEY
    default_channel: 'automation'
  - platform: webostv
    host: 192.168.10.135
    name: livingroom_tv
  - name: all_ios_devices
    platform: group
    services:
      - service: ios_iphone_von_dennis
      - service: ios_iphone_von_mary
      - service: ios_ipad

weather:
  - platform: yweather

automation: !include_dir_merge_list automations
binary_sensor: !include_dir_merge_list binary_sensor
device_tracker: !include_dir_merge_list device_tracker
emulated_hue: !include emulated_hue.yaml
group: !include_dir_merge_named groups
homekit: !include homekit.yaml
input_text: !include inputs/text.yaml
ios: !include ios.yaml
# light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_player
scene: !include_dir_merge_list scene
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensor
# switch: !include_dir_merge_list switch
