homeassistant:
  name: Zuhause
  latitude: !secret HOMEASSISTANT_LATITUDE
  longitude: !secret HOMEASSISTANT_LONGITUDE
  elevation: 350
  unit_system: metric
  time_zone: Europe/Berlin
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/tmp'
  auth_providers:
     - type: homeassistant
     - type: trusted_networks
       trusted_networks:
         - 192.168.10.0/24
         - 192.168.30.0/24
  external_url: !secret URL_HASS

default_config:
discovery:

custom_icons:

http:
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 10

downloader:
  download_dir: 'www/downloads'

ffmpeg:
  ffmpeg_bin: /usr/local/bin/ffmpeg

hacs:
  token: !secret GITHUB_ACCESS_TOKEN

wake_on_lan:

# logger:
#   default: info
#   logs:
#     homeassistant.components.alexa: debug
#     homeassistant.components.homekit: debug
#     pyhap: debug

recorder:
  purge_keep_days: 7
  purge_interval: 1
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - script
      - zone
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date

# calendar:
#   - platform: caldav
#     url: !secret CALDAV_URL_FAMILY
#     custom_calendars:
#       - name: Urlaub
#         calendar: Family
#         search: 'Urlaub'
frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate
    language: 'de'

tado:
  username: !secret TADO_USERNAME
  password: !secret TADO_PASSWORD

mqtt:
  # discovery: true
  # discovery_prefix: homeassistant
  broker: 192.168.10.150
  port: 1883
  client_id: !secret MQTT_CLIENT_ID
  username: !secret MQTT_USERNAME
  password: !secret MQTT_PASSWORD

nzbget:
  host: nzbget.local
  port: 6789

camera:
  - platform: ffmpeg
    name: arthur_cam
    input: -rtsp_transport tcp -i rtsp://192.168.10.161/unicast
  - platform: onvif
    name: Court Camera
    host: http://192.168.10.179:2020/onvif/device_service
    port: 2020
    username: !secret TAPO_USERNAME
    password: !secret TAPO_PASSWORD

device_tracker:
  - platform: unifi_direct
    host: 192.168.99.11
    username: dennis
    password: !secret UNIFI_SSH
  - platform: tado
    username: !secret TADO_USERNAME
    password: !secret TADO_PASSWORD
    home_id: !secret TADO_HOME_ID

homekit:
  name: HA Bridge
  filter:
    include_domains:
      - light
      - switch
      - media_player
    include_entities:
      - binary_sensor.door_window_sensor_158d00014dbac9
      - binary_sensor.door_window_sensor_158d0001f3a0f0

notify:
  - platform: webostv
    host: 192.168.10.135
    name: livingroom_tv
  - name: all_ios_devices
    platform: group
    services:
      - service: mobile_app_iphone_von_dennis
      - service: mobile_app_ipad_von_dennis_strasser
      - service: ios_iphone_von_mary
      - service: ios_ipad

vacuum:
  - platform: xiaomi_miio
    name: roborock_s50
    host: 192.168.10.166
    token: !secret ROBOROCK_TOKEN

weather:
  - platform: darksky
    api_key: !secret DARK_SKY_API_KEY
    mode: daily

webostv:
  host: 192.168.10.135
  name: LG TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret LG_TV_MAC

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret URL_HASSCONFIGURATOR
    require_admin: true
  plex:
    title: Plex
    icon: si:plex
    url: !secret URL_PLEX
    require_admin: true
  tautulli:
    title: Tautulli
    icon: mdi:filmstrip
    url: !secret URL_TAUTULLI
    require_admin: true
  nzbget:
    title: NZBGet
    icon: mdi:arrow-bottom-circle
    url: !secret URL_NZBGET
    require_admin: true
  radarr:
    title: Radarr
    icon: custom:radarr
    url: !secret URL_RADARR
    require_admin: true
  sonarr:
    title: Sonarr
    icon: custom:radarr
    url: !secret URL_SONARR
    require_admin: true
  zoneminder:
    title: ZoneMinder
    icon: mdi:video
    url: !secret URL_ZONEMINDER
    require_admin: true

alexa: !include alexa.yaml
automation: !include_dir_merge_list automations
group: !include_dir_merge_named groups
ios: !include ios.yaml
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensor
