automation:
  - alias: kz_nightlight
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      - condition: state
        entity_id: person.familie
        state: 'home'
    action:
      - service: light.turn_on
        entity_id: light.gateway_light_7811dcb8c5ed
        data_template:
          brightness: 50
          hs_color:
            - "{{ range(360)|random }}"
            - "{{ range(80,101)|random }}"
      - delay:
          hours: 12
      - service: light.turn_off
        entity_id: light.gateway_light_7811dcb8c5ed
