automation:
  - alias: arthur_temp_warn
    trigger:
      platform: numeric_state
      entity_id: sensor.temperature_158d0001574111
      below: 19
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: person.familie
          state: 'home'
        - condition: time
          after: '20:00:00'
          before: '00:30:00'
    action:
      - service: notify.notify
        data:
          title: 'Warnung!'
          message: 'Es ist zu kalt in Arthurs Zimmer!'
