automation:
  - alias: flur_button_evening_lighting
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d00013f85d3
          click_type: single
    action:
      - service: script.light_blink
        data:
          entity_id: light.flur_stehlampe
      - delay: '00:00:01'
      - service: script.cozy_lights
      - service: homeassistant.turn_off
        entity_id:
          - switch.kueche_licht
          - switch.bath_light1
          - switch.bath_light2
          - switch.toilett_light
          - switch.floor_light_wall
          - switch.floor_light_ceiling
          - switch.wz_light1
          - switch.wz_light2

  - alias: flur_button_good_night
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d00013f85d3
          click_type: double
    action:
      - service: script.light_blink
        data:
          entity_id: light.flur_stehlampe
      - delay: '00:00:01'
      - service: script.good_night

  - alias: flur_button_leave
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d00013f85d3
          click_type: long_click_press
    action:
      - service: script.light_blink
        data:
          entity_id: light.flur_stehlampe
      - delay: '00:00:01'
      - service: script.all_off
