- alias: wohnzimmer_auto_off
  trigger:
    - platform: state
      entity_id: group.wz_ambiente
      to: 'on'
      for:
        hours: 4
    - platform: state
      entity_id: switch.sonoff_wz_1
      to: 'on'
      for:
        hours: 4
    - platform: state
      entity_id: switch.sonoff_wz_2
      to: 'on'
      for:
        hours: 4
  action:
    - service: notify.livingroom_tv
      data:
        message: 'Achtung: Das Licht schaltet sich in 1 Minute aus'
        data:
          icon: '~/homeassistant/.homeassistant/www/icons/baseline-brightness_low.png'
    - delay:
        minutes: 1
    - service: homeassistant.turn_off
      entity_id:
        - group.wz_ambiente
        - switch.sonoff_wz_1
        - switch.sonoff_wz_2

- alias: wohnzimmer_tv_lights_on
  trigger:
    platform: state
    entity_id: media_player.lg_tv
    to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: group.wz_ambiente

- alias: wohnzimmer_tv_lights_off
  trigger:
    platform: state
    entity_id: media_player.lg_tv
    to: 'off'
  action:
    - delay:
        seconds: 30
    - service: homeassistant.turn_off
      entity_id: group.wz_ambiente

