- alias: Kinderzimmer Schlafbereich Nachts Licht AUS
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.sonoff_kz_2

- alias: Kinderzimmer Licht aus wenn Arthur Nachts aus dem Zimmer geht
  trigger:
    - platform: state
      entity_id: switch.sonoff_kz_1
      to: 'on'
      for:
        minutes: 2
    - platform: state
      entity_id: switch.sonoff_kz_2
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: time
      after: '23:00:00'
      before: '05:30:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.sonoff_kz_1
      - switch.sonoff_kz_2
      - light.gateway_light_7811dcb8c5ed
