- alias: Kinderzimmer Nachtlicht AN
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    - condition: state
      entity_id: group.familie
      state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.gateway_light_7811dcb8c5ed
      data:
        brightness: 50
        rgb_color: [255, 63, 0]

- alias: Kinderzimmer Nachtlicht AUS
  trigger:
    platform: time
    at: '06:00:00'
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_7811dcb8c5ed
