- platform: pilight
  switches:
    rf_kueche1:
      on_code:
        protocol: kaku_switch
        id: 5935104
        unit: 1
        'on': 1
      off_code:
        protocol: kaku_switch
        id: 5935104
        unit: 1
        'off': 0
      on_code_receive:
        protocol: arctech_switch
        id: 5935104
        unit: 1
        state: 'on'
      off_code_receive:
        protocol: arctech_switch
        id: 5935104
        unit: 1
        state: 'off'
    rf_kueche2:
      on_code:
        protocol: kaku_switch
        id: 5935104
        unit: 2
        'on': 1
      off_code:
        protocol: kaku_switch
        id: 5935104
        unit: 2
        'off': 0
      on_code_receive:
        protocol: arctech_switch
        id: 5935104
        unit: 2
        state: 'on'
      off_code_receive:
        protocol: arctech_switch
        id: 5935104
        unit: 2
        state: 'off'
    rf_wz_stehlampe:
      on_code:
        protocol: clarus_switch
        id: B3
        unit: 24
        'on': 1
      off_code:
        protocol: clarus_switch
        id: B3
        unit: 24
        'off': 0
      on_code_receive:
        protocol: clarus_switch
        id: B3
        unit: 24
        state: 'on'
      off_code_receive:
        protocol: clarus_switch
        id: B3
        unit: 24
        state: 'off'
    rf_wz_lichtkugel:
      on_code:
        protocol: kaku_switch
        id: 32969728
        unit: 1
        'on': 1
      off_code:
        protocol: kaku_switch
        id: 32969728
        unit: 1
        'off': 0
      on_code_receive:
        protocol: arctech_switch
        id: 32969728
        unit: 1
        state: 'on'
      off_code_receive:
        protocol: arctech_switch
        id: 32969728
        unit: 1
        state: 'off'
    rf_arthur_lichterkette:
      on_code:
        protocol: clarus_switch
        id: C7
        unit: 24
        'on': 1
      off_code:
        protocol: clarus_switch
        id: C7
        unit: 24
        'off': 0
      on_code_receive:
        protocol: clarus_switch
        id: C7
        unit: 24
        state: 'on'
      off_code_receive:
        protocol: clarus_switch
        id: C7
        unit: 24
        state: 'off'
    rf_sz_nachttisch:
      on_code:
        protocol: clarus_switch
        id: A3
        unit: 24
        'on': 1
      off_code:
        protocol: clarus_switch
        id: A3
        unit: 24
        'off': 0
      on_code_receive:
        protocol: clarus_switch
        id: A3
        unit: 24
        state: 'on'
      off_code_receive:
        protocol: clarus_switch
        id: A3
        unit: 24
        state: 'off'
