automation:
  - alias: sz_ks_ambient_motion_on
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002ec7e05
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.illumination_158d0002ec7e05
        below: 30
    action:
      service: homeassistant.turn_on
      entity_id: light.sz_ks_ambient_lights

  - alias: sz_ks_ambient_motion_off
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002ec7e05
      to: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: light.sz_ks_ambient_lights

  - alias: sz_ks_aqara_button
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000213540d
        click_type: single
    action:
      service: homeassistant.toggle
      entity_id: light.sz_ks_ambient_lights

  - alias: sz_ks_aqara_button_dbl
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000213540d
        click_type: double
    action:
      service: script.good_night
