- platform: mqtt
  name: "beleuchtung_flur"
  state_topic: "tele/floor/light/STATE"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/floor/light/POWER"
  availability_topic: "tele/floor/light/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "beleuchtung_toilette"
  state_topic: "tele/toilett/light/STATE"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/toilett/light/POWER"
  availability_topic: "tele/toilett/light/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "beleuchtung_esszimmer"
  state_topic: "tele/floor/light2/STATE"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/floor/light2/POWER"
  availability_topic: "tele/floor/light2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "beleuchtung_kueche"
  state_topic: "tele/kitchen/light/STATE"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/kitchen/light/POWER"
  availability_topic: "tele/kitchen/light/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
