default_view:
  name: Home
  view: yes
  icon: mdi:home
  entities:
    - camera.ffmpeg
    - climate.heizung
    - group.familie
    - group.flur
    - group.kueche
    - group.scenes
    - group.toilette
    - group.weather
    # - media_player.emby__kodi__kodi_libreelecwz
    - group.tv
    - media_player.volumio
