home_assistant:
  name: Home-Assistant
  control: hidden
  entities:
    - input_boolean.git_auto_update
    - script.git_update_config
    - script.gw_add_device
    #- uptime, prozessor usw
    #

bewegungsmelder:
  name: Bewegungsmelder
  control: hidden
  entities:
    - input_boolean.motion_sensor_flur_aktiv
    - input_boolean.motion_sensor_kueche_aktiv
    - input_boolean.motion_sensor_bad_aktiv
    - input_boolean.motion_sensor_toilette_aktiv

my_automations:
  name: Automatisierungen
  control: hidden
  entities:

