homeassistant:
  customize:
    switch.plug_158d0001530b1b:
      friendly_name: Beleuchtung
      icon: 'mdi:lightbulb-on-outline'
      extra_data_template: "${attributes.load_power !== 0 ? (attributes.load_power + 'W') : ''}"

sensor:
  - platform: template
    sensors:
      plug_158d0001530b1b_load_power:
        device_class: power
        unit_of_measurement: 'W'
        value_template: "{{ state_attr('switch.plug_158d0001530b1b', 'load_power')  }}"
      plug_158d0001530b1b_power_consumed:
        device_class: power
        unit_of_measurement: 'W/h'
        value_template: "{{ state_attr('switch.plug_158d0001530b1b', 'power_consumed')  }}"

input_boolean:
  aquarium_light_timer_aktiv:
    name: Timer aktiv
    initial: on
    icon: mdi:clock

input_datetime:
  aquarium_timer1_start:
    name: Zeit 1 EIN
    has_date: false
    has_time: true
    initial: '07:00'
    icon: mdi:clock-start

  aquarium_timer1_we_start:
    name: Zeit 1 EIN (Wochenende)
    has_date: false
    has_time: true
    initial: '09:00'
    icon: mdi:clock-start

  aquarium_timer1_end:
    name: Zeit 1 AUS
    has_date: false
    has_time: true
    initial: '12:00'
    icon: mdi:clock-end

  aquarium_timer2_start:
    name: Zeit 2 EIN
    has_date: false
    has_time: true
    initial: '16:00'
    icon: mdi:clock-start

  aquarium_timer2_end:
    name: Zeit 2 AUS
    has_date: false
    has_time: true
    initial: '19:00'
    icon: mdi:clock-end

  aquarium_timer2_we_end:
    name: Zeit 2 AUS (Wochenende)
    has_date: false
    has_time: true
    initial: '20:00'
    icon: mdi:clock-end

automation:
  - alias: aquarium_light_timer_on
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_timer1_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_timer2_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.aquarium_light_timer_aktiv
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      service: switch.turn_on
      entity_id: switch.plug_158d0001530b1b

  - alias: aquarium_light_timer_we_on
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_timer1_we_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_timer2_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.aquarium_light_timer_aktiv
        state: 'on'
      - condition: time
        weekday:
          - sat
          - sun
    action:
      service: switch.turn_on
      entity_id: switch.plug_158d0001530b1b

  - alias: aquarium_light_timer_off
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_timer1_end.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_timer2_end.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.aquarium_light_timer_aktiv
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      service: switch.turn_off
      entity_id: switch.plug_158d0001530b1b

  - alias: aquarium_light_timer_we_off
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_timer1_end.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_timer2_we_end.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.aquarium_light_timer_aktiv
        state: 'on'
      - condition: time
        weekday:
          - sat
          - sun
    action:
      service: switch.turn_off
      entity_id: switch.plug_158d0001530b1b
