automation:
  - alias: wz_ambient_auto_on
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: person.familie
        state: 'home'
    action:
      - service: light.turn_on
        entity_id: light.wz_lichtkugel
        data:
          brightness_pct: 55
          transition: 10
      - service: light.turn_on
        entity_id: light.wz_wand_led
        data_template:
          hs_color:
            - "{{ range(360)|random }}"
            - "{{ range(80,101)|random }}"
          brightness_pct: 100
          transition: 10
      - service: light.turn_on
        entity_id: light.wz_schreibtisch_led
        data:
          brightness_pct: 20
          transition: 10

  - alias: wz_ambient_auto_off
    trigger:
      platform: state
      entity_id: media_player.lg_tv
      to: 'off'
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
      - delay:
          minutes: 5
      - service: homeassistant.turn_off
        entity_id:
          - light.wz_lichtkugel
          - light.wz_wand_led
          - light.wz_schreibtisch_led
          - switch.wz_light1
          - switch.wz_light2

  - alias: wz_wall_auto_off
    trigger:
      - platform: state
        entity_id: light.wz_wand_led
        to: 'on'
        for:
          hours: 4
    action:
      - service: light.turn_off
        entity_id: light.wz_wand_led

  - alias: wz_schreibtisch_auto_off
    trigger:
      - platform: state
        entity_id: light.wz_schreibtisch_led
        to: 'on'
        for:
          hours: 4
    action:
      - service: light.turn_off
        entity_id: light.wz_schreibtisch_led

  - alias: wz_lichtkugel_auto_off
    trigger:
      - platform: state
        entity_id: light.wz_lichtkugel
        to: 'on'
        for:
          hours: 4
    action:
      - service: light.turn_off
        entity_id: light.wz_lichtkugel

  - alias: wz_watch_tv
    trigger:
      platform: state
      entity_id: media_player.lg_tv
      to: 'on'
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id: light.wz_wand_led
        data_template:
          brightness_pct: 50
          hs_color:
            - "{{ range(360)|random }}"
            - "{{ range(80,101)|random }}"
      - service: homeassistant.turn_on
        entity_id: light.wz_lichtkugel
        data:
          brightness_pct: 10
      - service: homeassistant.turn_off
        entity_id:
          - switch.wz_light1
          - switch.wz_light2


