automation:
  - alias: wz_tv_lights_on
    trigger:
      - platform: state
        entity_id: media_player.lg_tv
        to: 'playing'
      - platform: state
        entity_id: media_player.lg_tv
        to: 'on'
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: or
        conditions:
          - condition: state
            entity_id: media_player.lg_tv
            state: 'on'
          - condition: state
            entity_id: media_player.lg_tv
            state: 'playing'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.wz_ambilight

  - alias: wz_tv_lights_off
    trigger:
      platform: state
      entity_id: media_player.lg_tv
      to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.wz_ambilight
