automation:
  - alias: wz_left_single
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.wall_switch_left_158d00018337c3
          click_type: single
    action:
      - service: homeassistant.toggle
        entity_id: switch.wz_light1
      - delay:
          seconds: 1
      - condition: state
        entity_id: switch.wz_light1
        state: 'on'
      - service: homeassistant.turn_off
        entity_id:
          - light.wz_wand_led
          - light.wz_lichtkugel

  - alias: wz_right_single
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.wall_switch_right_158d00018337c3
          click_type: single
    action:
      service: switch.toggle
      entity_id: switch.wz_light2

  - alias: wz_both
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.wall_switch_both_158d00018337c3
          click_type: both
    action:
      - service: light.toggle
        entity_id: light.wz_schreibtisch_led

