- alias: all_off_when_nobody_home
  trigger:
    platform: state
    entity_id: group.motion_sensors
    to: 'off'
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: group.familie
      state: 'not_home'
  action:
    - service: script.all_off
