- alias: aquarium_light_timer_on
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_light_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: input_boolean.aquarium_light_timer_aktiv
    state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.plug_158d0001530b1b

- alias: aquarium_light_timer_off
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.aquarium_light_end.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    service: switch.turn_on
    entity_id: switch.plug_158d0001530b1b
