- alias: arthur_temp_warn
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_158d0001574111
    below: 18
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.familie
        state: 'home'
      - condition: time
        after: '20:00:00'
        before: '06:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.rf_sz_nachttisch
    - service: notify.notify
      data:
        title: 'Warnung!'
        message: 'Es ist zu kalt in Arthurs Zimmer!'
