- alias: door_open_bark_when_nobody_home
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00014dbac9
    to: 'on'
  action:
    service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: !secret XIAOMI_GATEWAY_MAC
      ringtone_id: 8
      ringtone_vol: 10
