- alias: door_open_reminder
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00014dbac9
    to: 'on'
    for:
      minutes: 8
  action:
    - service: notify.notify
      data:
        title: 'Eingangstür offen'
        message: 'Bitte schließen!'
    - service: script.flash_floor_lights
    - delay:
        seconds: 2
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret XIAOMI_GATEWAY_1_MAC
        ringtone_id: 11
        ringtone_vol: 50
