- alias: esszimmer_auto_off
  trigger:
    platform: state
    entity_id: switch.beleuchtung_esszimmer
    to: 'on'
    for:
      hours: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d0001e562ad
        state: 'off'
        for:
          minutes: 30
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d00012326f7
        state: 'off'
        for:
          minutes: 30
  action:
    service: homeassistant.turn_off
    entity_id: switch.beleuchtung_esszimmer
