- alias: flur_movement_on
  trigger:
    platform: state
    entity_id: binary_sensor.rf_motion_flur
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.stehlampe_flur
        state: 'off'
      - condition: state
        entity_id: input_boolean.motion_sensor_flur_aktiv
        state: 'on'
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 8
  action:
    service: script.yeelight_flur_weiss

- alias: flur_movement_off
  trigger:
    platform: state
    entity_id: binary_sensor.rf_motion_flur
    to: 'off'
    for:
      hours: 1
  condition:
    - condition: state
      entity_id: input_boolean.motion_sensor_flur_aktiv
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.stehlampe_flur
        - switch.beleuchtung_flur
