- alias: Guten Morgen Trigger
  trigger:
    platform: state
    entity_id: input_boolean.night_mode
    to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.wake_up
    - delay:
        seconds: 2
    - service: scene.turn_on
      entity_id: scene.gute_nacht
