- alias: hass_reboot
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.mobile_app_iphone_von_dennis
      data_template:
        title: "HASS Restart"
        message: "Home Assistant wurde neu gestartet"
    - service: frontend.set_theme
      data:
        name: ios-light-mode

- alias: 'Set dark theme for the night'
  trigger:
    platform: sun
    event: sunset
  action:
    - service: frontend.set_theme
      data:
        name: ios-dark-mode
