- alias: kueche_movement_on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00012326f7
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.motion_sensor_kueche_aktiv
        state: 'on'
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 8
      - condition: state
        entity_id: switch.rf_kueche2
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.beleuchtung_kueche

- alias: kueche_movement_off
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00012326f7
    to: 'off'
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.motion_sensor_kueche_aktiv
      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.beleuchtung_kueche

- alias: kueche_movement_volumio_on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00012326f7
    to: 'on'
  condition:
    - condition: time
      after: '06:00:00'
      before: '20:00:00'
  action:
    service: media_player.media_play
    entity_id: media_player.volumio
