################################################
# Automatisches Ausschalten der Lichter nach
# einer bestimmten Zeit
#
- alias: Toilette Auto-OFF
  trigger:
    platform: state
    entity_id: light.beleuchtung_toilette
    to: 'on'
    for:
      minutes: 10
  action:
    - service: homeassistant.turn_off
      entity_id: light.beleuchtung_toilette

- alias: Küche Auto-OFF
  trigger:
    platform: state
    entity_id: light.beleuchtung_kueche
    to: 'on'
    for:
      hours: 2
  action:
    - service: homeassistant.turn_off
      entity_id: light.beleuchtung_kueche

- alias: Flur Auto-OFF
  trigger:
    platform: state
    entity_id: light.beleuchtung_flur
    to: 'on'
    for:
      hours: 2
  action:
    - service: homeassistant.turn_off
      entity_id: light.beleuchtung_flur

- alias: Flur Stehlampe Auto-OFF
  trigger:
    platform: state
    entity_id: light.stehlampe_flur
    to: 'on'
    for:
      hours: 2
  action:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - service: light.turn_off
      entity_id: light.stehlampe_flur
      data:
        transition: 30

- alias: Esszimmer Auto-OFF
  trigger:
    platform: state
    entity_id: light.beleuchtung_esszimmer
    to: 'on'
    for:
      hours: 2
  action:
    - service: homeassistant.turn_off
      entity_id: light.beleuchtung_esszimmer
