- alias: Verstecke LG TV wenn aus
  trigger:
    - platform: state
      entity_id: media_player.lg_tv
      to: 'off'
  action:
    service: group.set_visibility
    entity_id: group.tv
    data:
      visible: false

- alias: Zeige LG TV wenn eingeschaltet
  trigger:
    - platform: state
      entity_id: media_player.lg_tv
      to: 'playing'
  action:
    service: group.set_visibility
    entity_id: group.tv
    data:
      visible: true
