- alias: nightlight_on
  trigger:
    platform: sun
    event: sunset
    offset: '01:00:00'
  condition:
    - condition: state
      entity_id: group.familie
      state: 'home'
  action:
    - service: script.gateway_nightlight_on

- alias: nightlight_off
  trigger:
    platform: sun
    event: sunrise
    offset: '01:00:00'
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_286c0788a9dd
