- alias: Verstecke Dennis wenn nicht Zuhause
  trigger:
    platform: state
    entity_id: group.person_dennis
    from: 'home'
    to: 'not_home'
  action:
    service: group.set_visibility
    entity_id: group.person_dennis
    data:
      visible: false

- alias: Zeige Dennis wenn Zuhause
  trigger:
    platform: state
    entity_id: group.person_dennis
    from: 'not_home'
    to: 'home'
  action:
    service: group.set_visibility
    entity_id: group.person_dennis
    data:
      visible: true

- alias: Verstecke Mary wenn nicht Zuhause
  trigger:
    platform: state
    entity_id: group.person_mary
    from: 'home'
    to: 'not_home'
  action:
    - service: group.set_visibility
      entity_id: group.person_mary
      data:
        visible: false
    - service: notify.slack
      data_template:
        title: "Mary hat das Haus verlassen"
        message: "Mary hat das Haus verlassen"

- alias: Zeige Mary wenn Zuhause
  trigger:
    platform: state
    entity_id: group.person_mary
    from: 'not_home'
    to: 'home'
  action:
    - service: group.set_visibility
      entity_id: group.person_mary
      data:
        visible: true
    - service: notify.slack
      data_template:
        title: "Mary ist nach Hause gekommen"
        message: "Mary ist nach Hause gekommen"
