- alias: smart_button_single_click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00013f85d3
      click_type: single
  action:
    service: switch.toggle
    entity_id: switch.rf_sz_nachttisch

- alias: smart_button_long_press
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00013f85d3
      click_type: long_click_press
  action:
    service: script.all_off
