- alias: weihnachtsbaum_on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001e562ad
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.rf_floor_weihnachtsbaum

- alias: weihnachtsbaum_off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e562ad
      to: 'off'
      for:
        minutes: 60
    - platform: state
      entity_id: switch.floor_light_ceiling
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.motion_sensor_flur_aktiv
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.rf_floor_weihnachtsbaum
