automation:
  - alias: bad_movement_on
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e516a5
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.motion_sensor_bad_aktiv
          state: 'on'
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          below: 8
    action:
      service: homeassistant.turn_on
      entity_id: switch.bath_light1

  - alias: bad_movement_off
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e516a5
      to: 'off'
      for:
        minutes: 15
    condition:
      - condition: state
        entity_id: input_boolean.motion_sensor_bad_aktiv
        state: 'on'
    action:
      service: homeassistant.turn_off
      entity_id: switch.bath_light1
