homeassistant:
  customize:
    switch.bath_light1:
      friendly_name: Beleuchtung
      icon: 'mdi:ceiling-light'
    switch.bath_light2:
      friendly_name: Spiegel / Steckdose
      icon: 'mdi:lightbulb-on-outline'
    binary_sensor.door_window_sensor_158d0001f3a0f0:
      friendly_name: Fenster
      icon: 'mdi:window-closed'
      show_last_changed: true

group:
  bad:
    name: Badezimmer
    control: hidden
    entities:
      - sensor.temperature_158d0001c2c57f
      - sensor.humidity_158d0001c2c57f
      - binary_sensor.door_window_sensor_158d0001f3a0f0
      - sensor.motion_sensor_bad_last_seen
      - switch.bath_light1
      - switch.bath_light2

sensor:
  - platform: template
    sensors:
      motion_sensor_bad_last_seen:
        friendly_name: 'Letzte Bewegung'
        icon_template: 'mdi:clock-alert'
        value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d0001e516a5.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'

switch:
  - platform: mqtt
    name: bath_light1
    command_topic: cmnd/bad/POWER1
    state_topic: stat/bad/RESULT
    value_template: '{{value_json.POWER1}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/bad/LWT
    payload_available: Online
    payload_not_available: Offline

  - platform: mqtt
    name: bath_light2
    command_topic: cmnd/bad/POWER2
    state_topic: stat/bad/RESULT
    value_template: '{{value_json.POWER2}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/bad/LWT
    payload_available: Online
    payload_not_available: Offline

automation:
  - alias: bad_movement_on
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e516a5
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.motion_sensor_bad_aktiv
          state: 'on'
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          below: 8
    action:
      service: homeassistant.turn_on
      entity_id: switch.bath_light1

  - alias: bad_movement_off
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e516a5
      to: 'off'
      for:
        minutes: 15
    condition:
      - condition: state
        entity_id: input_boolean.motion_sensor_bad_aktiv
        state: 'on'
    action:
      service: homeassistant.turn_off
      entity_id: switch.bath_light1

  - alias: bad_humidity_too_high
    trigger:
      platform: numeric_state
      entity_id: sensor.humidity_158d0001c2c57f
      above: 70
      for:
        minutes: 15
    condition:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0001f3a0f0
        state: 'off'
    action:
      ############# Ab hier nur vor 20:00 Uhr ####################################
      - condition: time
        before: '20:00:00'
      # - service: media_player.volume_set
      #   entity_id: media_player.volumio
      #   data_template:
      #     volume_level: 0.65
      - service: media_player.play_media
        data:
          entity_id: media_player.volumio_mpd
          media_content_id: "https://hass.derstrassi.net/local/sounds/two-tone-chime.mp3"
          media_content_type: "music"
      - delay:
          seconds: 5
      - service: tts.google_say
        entity_id: media_player.volumio_mpd
        data_template:
          message: "Die Luftfeuchtigkeit im Bad ist aktuell bei {{ states.sensor.humidity_158d0001c2c57f.state }}%, bitte lüften!"
      - delay:
          seconds: 8
      # - service: media_player.volume_set
      #   entity_id: media_player.volumio
      #   data_template:
      #     volume_level: 0.2

  - alias: bad_zahnbuerste_laden
    trigger:
      platform: time
      at: '10:00:00'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.bath_light2
      - delay:
          hours: 3
      - service: homeassistant.turn_off
        entity_id: switch.bath_light2

