switch:
  - platform: mqtt
    name: kz_light1
    command_topic: cmnd/kz/light1/POWER
    state_topic: stat/kz/light1/RESULT
    value_template: '{{value_json.POWER}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/kz/light1/LWT
    payload_available: Online
    payload_not_available: Offline

  - platform: mqtt
    name: kz_light2
    command_topic: cmnd/kz/light2/POWER
    state_topic: stat/kz/light2/RESULT
    value_template: '{{value_json.POWER}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/kz/light2/LWT
    payload_available: Online
    payload_not_available: Offline

automation:
  - alias: Arthur macht in der Nacht das Licht an
    trigger:
      - platform: state
        entity_id: switch.kz_light1
        to: 'on'
      - platform: state
        entity_id: switch.kz_light2
        to: 'on'
    condition:
      - condition: time
        after: '22:00:00'
        before: '06:00:00'
    action:
      - service: light.turn_on
        entity_id: light.gateway_light_286c0788a9dd
        data:
          rgb_color: [255,100,100]
          brightness_pct: 100
      - service: script.yeelight_flur_weiss

  - alias: Kinderzimmer Schlafbereich Nachts Licht AUS
    trigger:
      platform: time
      at: '23:00:00'
    action:
      service: homeassistant.turn_off
      entity_id:
        - switch.kz_light2

  - alias: Kinderzimmer Nachtlicht
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      - condition: state
        entity_id: person.familie
        state: 'home'
    action:
      - service: light.turn_on
        entity_id: light.gateway_light_7811dcb8c5ed
        data:
          brightness: 50
          rgb_color: [255, 63, 0]
      - delay:
          hours: 12
      - service: light.turn_off
        entity_id: light.gateway_light_7811dcb8c5ed

  - alias: arthur_temp_warn
    trigger:
      platform: numeric_state
      entity_id: sensor.temperature_158d0001574111
      below: 18
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: person.familie
          state: 'home'
        - condition: time
          after: '20:00:00'
          before: '00:30:00'
    action:
      - service: notify.notify
        data:
          title: 'Warnung!'
          message: 'Es ist zu kalt in Arthurs Zimmer!'

  - alias: kz_left_single
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00012a7f6a
        click_type: single
    action:
      service: switch.toggle
      entity_id: switch.kz_light1

  - alias: kz_right_single
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d00012a7f6a
        click_type: single
    action:
      service: switch.toggle
      entity_id: switch.kz_light2

  - alias: kz_both_click
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_both_158d00012a7f6a
        click_type: both
    action:
      service: switch.toggle
      entity_id: switch.plug_158d0001530b1b

