switch:
  - platform: mqtt
    name: kitchen_light
    command_topic: cmnd/kitchen/light/POWER
    state_topic: stat/kitchen/light/RESULT
    value_template: '{{value_json.POWER}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/kitchen/light/LWT
    payload_available: Online
    payload_not_available: Offline

automation:
  - alias: kueche_movement_on
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d00012326f7
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.motion_sensor_kueche_aktiv
          state: 'on'
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          below: 12
    action:
      service: homeassistant.turn_on
      entity_id: switch.kitchen_light

  - alias: kueche_movement_off
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d00012326f7
      to: 'off'
      for:
        minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.motion_sensor_kueche_aktiv
        state: 'on'
    action:
      service: homeassistant.turn_off
      entity_id: switch.kitchen_light
