switch:
  - platform: mqtt
    name: sz_light
    command_topic: shellies/shelly1-2C784C/relay/0/command
    state_topic: shellies/shelly1-2C784C/relay/0
    payload_off: 'off'
    payload_on: 'on'
    state_off: 'off'
    state_on: 'on'

light:
  - platform: flux_led
    devices:
      192.168.10.152:
        name: sz_ks_led1
        mode: 'w'
        protocol: 'ledenet'
      192.168.10.153:
        name: sz_ks_led2
        mode: 'w'
        protocol: 'ledenet'

  - platform: group
    name: sz_ks_ambient_lights
    entities:
      - light.sz_ks_led1
      - light.sz_ks_led2

automation:
  - alias: sz_lights_on
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002ec8058
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.illumination_158d0002ec8058
        below: 30
      - condition: time
        after: '06:00:00'
    action:
      service: homeassistant.turn_on
      entity_id: switch.sz_light

  - alias: sz_lights_on_night_mode
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002ec8058
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.illumination_158d0002ec8058
        below: 30
      - condition: time
        before: '06:00:00'
    action:
      service: homeassistant.turn_on
      entity_id: switch.sz_light

  - alias: sz_lights_auto_off
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002ec8058
      to: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: switch.sz_light

  - alias: sz_ks_ambient_motion_on
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002ec7e05
      to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.sz_ks_ambient_lights

  - alias: sz_ks_ambient_motion_off
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002ec7e05
      to: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: light.sz_ks_ambient_lights

  - alias: sz_ks_aqara_button
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000213540d
        click_type: single
    action:
      service: homeassistant.toggle
      entity_id: light.sz_ks_ambient_lights
