automation:
  - alias: activate_alarm
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SOUND_ALARM
    action:
      - service: light.turn_on
        entity_id: light.floor_yeelight
        data:
          effect: Alarm
      - service: light.turn_on
        entity_id: light.gateway_light_286c0788a9dd
        data:
          color_name: red
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret XIAOMI_GATEWAY_1_MAC
          ringtone_id: 8
          ringtone_vol: 80
      - delay:
          seconds: 10
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret XIAOMI_GATEWAY_1_MAC
          ringtone_id: 8
          ringtone_vol: 90
      - delay:
          minutes: 10
      - service: light.turn_off
        entity_id: light.floor_yeelight
      - service: light.turn_off
        entity_id: light.gateway_light_286c0788a9dd

  - alias: door_open_bark_when_nobody_home
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d00014dbac9
      to: 'on'
    condition:
      - condition: state
        entity_id: person.familie
        state: 'not_home'
    action:
      - service: notify.notify
        data:
          title: 'Unbefugtes Betreten der Wohnung'
          message: 'Jemand hat soeben die Wohnung betreten'
          data:
            push:
              category: "alarm"
