media_player:
  - platform: denonavr
    host: 192.168.10.154
    zones:
      - zone: Zone2

switch:
  - platform: pilight
    switches:
      rf_wz_subwoofer:
        on_code:
          protocol: clarus_switch
          id: B3
          unit: 24
          'on': 1
        off_code:
          protocol: clarus_switch
          id: B3
          unit: 24
          'off': 0
        on_code_receive:
          protocol: clarus_switch
          id: B3
          unit: 24
          state: 'on'
        off_code_receive:
          protocol: clarus_switch
          id: B3
          unit: 24
          state: 'off'

automation:
  - alias: wz_subwoofer_on
    trigger:
      - platform: state
        entity_id: media_player.denon_avr_x1100w
        to: 'on'
      - platform: state
        entity_id: media_player.denon_avr_x1100w
        to: 'playing'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.rf_wz_subwoofer
  - alias: wz_subwoofer_off
    trigger:
      - platform: state
        entity_id: media_player.denon_avr_x1100w
        to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.rf_wz_subwoofer
