media_player:
  - platform: denonavr
    host: 192.168.10.155
    zones:
      - zone: Zone2

switch:
  - platform: mqtt
    name: wz_subwoofer
    command_topic: cmnd/wz/lichtkugel/POWER
    state_topic: stat/wz/lichtkugel/RESULT
    value_template: '{{value_json.POWER}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/wz/lichtkugel/LWT
    payload_available: Online
    payload_not_available: Offline

automation:
  - alias: wz_subwoofer_on
    trigger:
      - platform: state
        entity_id: media_player.denon_avr_x1100w
        to: 'on'
      - platform: state
        entity_id: media_player.denon_avr_x1100w
        to: 'playing'
    condition:
      - condition: time
        after: '08:00:00'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.wz_subwoofer

  - alias: wz_subwoofer_off
    trigger:
      - platform: state
        entity_id: media_player.denon_avr_x1100w
        to: 'off'
    action:
      - delay:
          minutes: 15
      - condition: state
        entity_id: media_player.denon_avr_x1100w
        state: 'off'
      - service: homeassistant.turn_off
        entity_id: switch.wz_subwoofer
