homeassistant:
  customize:
    script.git_update_config:
      icon: 'mdi:cloud-download'
    input_boolean.git_auto_update:
      icon: 'mdi:git'

group:
  ha:
    name: Home-Assistant
    entities:
      - input_boolean.git_auto_update
      - script.git_update_config

input_boolean:
  git_auto_update:
    name: Auto-Update HA Config
    icon: mdi:git

script:
  git_update_config:
    alias: Update HA Config
    sequence:
      - service: persistent_notification.dismiss
        data:
          notification_id: "update_avail"
      - service: shell_command.git_pull
      - service: homeassistant.restart

shell_command:
  git_pull: /bin/sh /root/.homeassistant/shell_scripts/git_pull.sh

automation:
  - alias: git_push_webhook
    trigger:
      platform: webhook
      webhook_id: github_push
    action:
      - condition: state
        entity_id: input_boolean.git_auto_update
        state: 'on'
      - service: persistent_notification.create
        data:
          title: "Update verfügbar!"
          message: "Bitte Konfiguration updaten!"
          notification_id: "update_avail"
      - service: script.git_update_config


