homeassistant:
  customize:
    script.git_update_config:
      icon: 'mdi:cloud-download'
    input_boolean.git_auto_update:
      icon: 'mdi:git'

group:
  ha:
    name: Home-Assistant
    control: hidden
    entities:
      - input_boolean.git_auto_update
      - script.git_update_config

input_boolean:
  git_auto_update:
    name: Auto-Update HA Config
    icon: mdi:git

script:
  check_for_updates:
    sequence:
      - service: customizer.set_attribute
        data:
          entity_id: script.git_update_config
          attribute: hidden
          value: 1
      - service: shell_command.git_update_new_commits_sensor
      - condition: numeric_state
        entity_id: sensor.new_commits
        above: 0
      - service: persistent_notification.create
        data:
          title: "Update verfügbar!"
          message: "Bitte Konfiguration updaten!"
          notification_id: "update_avail"
      - service: customizer.set_attribute
        data:
          entity_id: script.git_update_config
          attribute: hidden
          value: 0
  git_update_config:
    alias: Update HA Config
    sequence:
      - service: persistent_notification.dismiss
        data:
          notification_id: "update_avail"
      - service: shell_command.git_pull
      - service: homeassistant.restart

sensor:
  - platform: template
    sensors:
      new_commits:
        value_template: >-
          {{ states("sensor.new_commits") }}

shell_command:
  git_pull: ~/.homeassistant/shell_scripts/git_pull.sh
  git_update_new_commits_sensor: ~/.homeassistant/shell_scripts/git_update_new_commits_sensor.sh

automation:
  - alias: git_update_check
    trigger:
      platform: time
      minutes: '/1'
      seconds: 0
    condition:
      condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.new_commits
          below: 1
        - condition: state
          entity_id: sensor.new_commits
          state: 'unknown'
    action:
      - service: script.check_for_updates
      - condition: state
        entity_id: input_boolean.git_auto_update
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.new_commits
        above: 0
      - service: script.git_update_config


