homeassistant:
  customize:
    switch.klingel:
      friendly_name: Tür-Klingel
    switch.tuer_oeffner:
      friendly_name: Tür-Öffner
      icon: 'mdi:door-open'

input_text:
  klingel_random:
    name: klingel_random

automation:
  - alias: klingel_open_door
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: OPEN_DOOR
    action:
      - service: switch.turn_on
        entity_id: switch.tuer_oeffner

  - alias: klingel_me_at_home
    trigger:
      platform: state
      entity_id: device_tracker.iphone_von_dennis
      to: 'home'
    action:
      - service: notify.ios_iphone_von_dennis
        data:
          title: 'Welcome Home'
          message: 'Möchtest du die Tür öffnen?'
          data:
            push:
              category: 'klingel'

  - alias: klingel_notify
    trigger:
      platform: state
      entity_id: switch.klingel
      to: 'on'
    action:
      - service: input_text.set_value
        entity_id: input_text.klingel_random
        data_template:
          value: >-
            {%- macro random_int(len) -%}
              {%- for n in range(len) -%}
                {{ [0,1,2,3,4,5,6,7,8,9]|random }}
              {%- endfor -%}
            {%- endmacro -%}
            {%- set parts = [random_int(8), random_int(4), random_int(4), random_int(4), random_int(12)] -%}
            {{ parts|join('-') }}
      - service: camera.snapshot
        entity_id: camera.arthur_cam
        data:
          filename: '/home/homeassistant/.homeassistant/www/snapshots/front_door/cam_{{ states("input_text.klingel_random") }}.jpg'
      - service: notify.notify
      # - service: notify.ios_iphone_von_dennis
        data_template:
          title: 'Klingeling...'
          message: 'Jemand hat die Türklingel betätigt'
          data:
            push:
              category: klingel
            attachment:
              url: 'https://hass.derstrassi.net/local/snapshots/front_door/cam_{{ states("input_text.klingel_random") }}.jpg'
              content-type: jpg

  - alias: klingel_sound
    trigger:
      platform: state
      entity_id: switch.klingel
      to: 'on'
    condition:
      - condition: time
        after: '06:00:00'
        before: '20:00:00'
      - condition: state
        entity_id: group.familie
        state: 'home'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret XIAOMI_GATEWAY_1_MAC
          ringtone_id: 10
          ringtone_vol: 35

  - alias: klingel_nachts
    trigger:
      platform: state
      entity_id: switch.klingel
      to: 'on'
    condition:
      - condition: time
        after: '20:00:00'
        before: '06:00:00'
      - condition: state
        entity_id: group.familie
        state: 'home'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret XIAOMI_GATEWAY_1_MAC
          ringtone_id: 10
          ringtone_vol: 2
      ## Licht blinken lassen
