switch:
  - platform: mqtt
    name: door_opener
    command_topic: cmnd/floor/light/POWER2
    state_topic: stat/floor/light/RESULT
    value_template: '{{value_json.POWER2}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/floor/light/LWT
    payload_available: Online
    payload_not_available: Offline

  - platform: mqtt
    name: klingel
    command_topic: cmnd/floor/light/POWER3
    state_topic: stat/floor/light/RESULT
    value_template: '{{value_json.POWER3}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/floor/light/LWT
    payload_available: Online
    payload_not_available: Offline

timer:
  klingel_cycle:
    duration: '00:00:05'
  # return_home:
  #   duration: '00:30:00'

script:
  doorbell:
    sequence:
      - service: xiaomi_aqara.play_ringtone
        data_template:
          gw_mac: !secret XIAOMI_GATEWAY_1_MAC
          ringtone_id: '{{ ringtone_id }}'
          ringtone_vol: >-
            {%- if states('sensor.time') > '05:59' and states('sensor.time') < '20:00' -%}
              35
            {%- else -%}
              2
            {%- endif -%}

automation:
  - alias: doorbell_open_door
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: OPEN_DOOR
    action:
      - service: switch.turn_on
        entity_id: switch.door_opener

  # - alias: start_return_home_timer
  #   trigger:
  #     platform: state
  #     entity_id: person.dennis_strasser
  #     to: 'home'
  #   action:
  #     - service: timer.start
  #       entity_id: timer.return_home

  # - alias: doorbell_ask_for_door_open
  #   trigger:
  #     platform: state
  #     entity_id: person.dennis_strasser
  #     to: 'home'
  #   action:
  #     - service: notify.ios_iphone_von_dennis
  #       data:
  #         title: 'Wilkommen Zuhause!'
  #         message: 'Möchtest du die Tür öffnen?'
  #         data:
  #           push:
  #             category: 'klingel'

  - alias: doorbell_notify
    trigger:
      platform: state
      entity_id: switch.klingel
      to: 'on'
    condition:
      # prevent multiple consecutive presses
      - condition: state
        entity_id: timer.klingel_cycle
        state: 'idle'
    action:
      - service: timer.start
        entity_id: timer.klingel_cycle
      - service: script.doorbell
        data:
          ringtone_id: 10
      - service: notify.livingroom_tv
        data:
          message: 'Klingel: Haustür unten'
          data:
            icon: '/root/.homeassistant/www/icons/baseline-notifications_active.png'
      # - service: camera.snapshot
      #   entity_id: camera.haustur
      #   data:
      #     filename: '/root/.homeassistant/www/downloads/ring/snapshots/{{ states("input_text.ring_random") }}.jpg'
      # - delay:
      #     seconds: 5
      - service: notify.all_ios_devices
        data_template:
          title: 'Klingeling...'
          message: 'Jemand wartet an der Tür!'
          data:
            # url: https://google.de # ring app url, have to reverse-engineer
            push:
              category: klingel
            # attachment:
            #   url: 'https://hass.derstrassi.net/local/downloads/ring/snapshots/{{ states("input_text.ring_random") }}.jpg'
            #   content-type: jpg
