homeassistant:
  customize:
    switch.klingel:
      friendly_name: Tür-Klingel
    switch.tuer_oeffner:
      friendly_name: Tür-Öffner
      icon: 'mdi:door-open'

ios:
  push:
    categories:
      - name: Klingel
        identifier: 'KLINGEL'
        actions:
          - identifier: 'OPEN_DOOR'
            title: 'Tür Öffnen'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'IGNORE'
            title: 'Ignorieren'

automation:
  - alias: klingel_open_door
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: OPEN_DOOR
    action:
      - service: switch.turn_on
        entity_id: switch.tuer_oeffner

  - alias: klingel_me_at_home
    trigger:
      platform: state
      entity_id: device_tracker.iphone_von_dennis
      to: 'home'
    action:
      - service: notify.ios_iphone_von_dennis
        data:
          title: 'Welcome Home'
          message: 'Möchtest du die Tür öffnen?'
          push:
            category: "KLINGEL"

  - alias: klingel_notify
    trigger:
      platform: state
      entity_id: switch.klingel
      to: 'on'
    action:
      - service: notify.notify
        data:
          title: 'Klingeling...'
          message: 'Jemand hat die Türklingel betätigt'
          push:
            category: "KLINGEL"
          attachment:
            content-type: jpeg
          entity_id: camera.arthur_cam

  - alias: klingel_sound
    trigger:
      platform: state
      entity_id: switch.klingel
      to: 'on'
    action:
      - condition: time
        after: '06:00:00'
        before: '20:00:00'
      - condition: state
        entity_id: group.familie
        state: 'home'
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret XIAOMI_GATEWAY_1_MAC
          ringtone_id: 10
          ringtone_vol: 40

  - alias: klingel_nachts
    trigger:
      platform: state
      entity_id: switch.klingel
      to: 'on'
    action:
      - condition: time
        after: '20:00:00'
        before: '06:00:00'
      - condition: state
        entity_id: group.familie
        state: 'home'
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret XIAOMI_GATEWAY_1_MAC
          ringtone_id: 10
          ringtone_vol: 2
      ## Licht blinken lassen
