homeassistant:
  customize:
    switch.klingel:
      friendly_name: Klingel Wohnung
      icon: mdi:bell
    switch.door_opener:
      friendly_name: Tür-Öffner
      icon: mdi:door-open
    binary_sensor.ring_haustur_ding:
      friendly_name: Klingel Haus
      icon: mdi:bell
    binary_sensor.ring_haustur_motion:
      friendly_name: Bewegung Haustür

switch:
  - platform: mqtt
    name: door_opener
    command_topic: cmnd/floor/light/POWER2
    state_topic: stat/floor/light/RESULT
    value_template: '{{value_json.POWER2}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/floor/light/LWT
    payload_available: Online
    payload_not_available: Offline

binary_sensor:
  - platform: ring
    name: ring
    monitored_conditions:
      - ding
      - motion

# input_text:
#   klingel_random:
#     name: klingel_random

timer:
  klingel_cycle:
    duration: '00:00:05'
  return_home:
    duration: '00:30:00'

script:
  doorbell:
    sequence:
      - service: xiaomi_aqara.play_ringtone
        data_template:
          gw_mac: !secret XIAOMI_GATEWAY_1_MAC
          ringtone_id: '{{ ringtone_id }}'
          ringtone_vol: >-
            {%- if states('sensor.time') > '05:59' and states('sensor.time') < '20:00' -%}
              35
            {%- else -%}
              2
            {%- endif -%}
  # doorbell_set_random:
  #   sequence:
  #     - service: input_text.set_value
  #       entity_id: input_text.klingel_random
  #       data_template:
  #         value: >-
  #           {%- macro random_int(len) -%}
  #             {%- for n in range(len) -%}
  #               {{ [0,1,2,3,4,5,6,7,8,9]|random }}
  #             {%- endfor -%}
  #           {%- endmacro -%}
  #           {%- set parts = [random_int(8), random_int(4), random_int(4), random_int(4), random_int(12)] -%}
  #           {{ parts|join('-') }}

automation:
  - alias: doorbell_open_door
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: OPEN_DOOR
    action:
      - service: switch.turn_on
        entity_id: switch.door_opener

  - alias: start_return_home_timer
    trigger:
      platform: state
      entity_id: group.person_dennis
      to: 'home'
    action:
      - service: timer.start
        entity_id: timer.return_home

  - alias: doorbell_ask_for_door_open
    trigger:
      platform: state
      entity_id: group.person_dennis
      to: 'home'
    action:
      - service: notify.ios_iphone_von_dennis
        data:
          title: 'Wilkommen Zuhause!'
          message: 'Möchtest du die Tür öffnen?'
          data:
            push:
              category: 'klingel'

  # - alias: doorbell_download_last_motion_video
  #   trigger:
  #     platform: state
  #     entity_id: binary_sensor.ring_haustur_motion
  #     to: 'on'
  #   action:
  #     - delay:
  #         seconds: 60
  #     - service: downloader.download_file
  #       data_template:
  #         url: '{{ states.camera.haustur.attributes.video_url }}'
  #         subdir: 'front_door'
  #         filename: 'last_motion.mp4'
  #         overwrite: true

  # - alias: doorbell_download_last_ring_video
  #   trigger:
  #     platform: state
  #     entity_id: binary_sensor.ring_haustur_ding
  #     to: 'on'
  #   action:
  #     - delay:
  #         seconds: 90
  #     - service: script.doorbell_set_random
  #     - service: downloader.download_file
  #       data_template:
  #         url: '{{ states.camera.haustur.attributes.video_url }}'
  #         subdir: 'front_door'
  #         filename: '{{ states("input_text.klingel_random") }}.mp4'

  - alias: doorbell_haus_notify
    trigger:
      platform: state
      entity_id: binary_sensor.ring_haustur_ding
      to: 'on'
    condition:
      # prevent multiple consecutive presses
      - condition: state
        entity_id: timer.klingel_cycle
        state: 'idle'
    action:
      - service: timer.start
        entity_id: timer.klingel_cycle
      - service: notify.notify
        data_template:
          title: 'Klingeling...'
          message: 'Jemand wartet an der Haustür'
          data:
            # url: https://google.de # ring app url, have to reverse-engineer
            push:
              category: klingel
      - condition: state
        entity_id: group.familie
        state: 'home'
      - service: script.doorbell
        data:
          ringtone_id: 10
      - service: notify.livingroom_tv
        data:
          message: 'Klingel: Haustür unten'
          data:
            icon: '~/.homeassistant/www/icons/baseline-notifications_active.png'
      ## Licht blinken lassen

  - alias: doorbell_wohnung_notify
    trigger:
      platform: state
      entity_id: switch.klingel
      to: 'on'
    condition:
      # prevent multiple consecutive presses
      - condition: state
        entity_id: timer.klingel_cycle
        state: 'idle'
    action:
      - service: timer.start
        entity_id: timer.klingel_cycle
      # - service: input_text.set_value
      #   entity_id: input_text.klingel_random
      #   data_template:
      #     value: >-
      #       {%- macro random_int(len) -%}
      #         {%- for n in range(len) -%}
      #           {{ [0,1,2,3,4,5,6,7,8,9]|random }}
      #         {%- endfor -%}
      #       {%- endmacro -%}
      #       {%- set parts = [random_int(8), random_int(4), random_int(4), random_int(4), random_int(12)] -%}
      #       {{ parts|join('-') }}
      # - service: camera.snapshot
      #   entity_id: camera.arthur_cam
      #   data:
      #     filename: '~/homeassistant/.homeassistant/www/snapshots/front_door/{{ states("input_text.klingel_random") }}.jpg'
      - service: notify.notify
      # - service: notify.ios_iphone_von_dennis
        data_template:
          title: 'Klingeling...'
          message: 'Jemand wartet vor der Wohnungstür'
          # data:
          #   push:
          #     category: klingel
            # attachment:
            #   url: 'https://hass.derstrassi.net/local/snapshots/front_door/{{ states("input_text.klingel_random") }}.jpg'
            #   content-type: jpg
      - condition: state
        entity_id: group.familie
        state: 'home'
      - service: script.doorbell
        data:
          ringtone_id: 11
      - service: notify.livingroom_tv
        data:
          message: 'Klingel: Wohnungstür'
          data:
            icon: '~/.homeassistant/www/icons/baseline-notifications_active.png'
      ## Licht blinken lassen
