homeassistant:
  customize:
    sensor.pool_temperatur:
      friendly_name: Wassertemperatur
      icon: mdi:oil-temperature
    switch.pool:
      friendly_name: Filterpumpe
      icon: mdi:gauge

sensor:
  - platform: mqtt
    name: pool_temperatur
    availability_topic: "tele/garden/pool/LWT"
    state_topic: "tele/garden/pool/SENSOR"
    unit_of_measurement: "°C"
    expire_after: 600
    value_template: "{{ value_json.DS18B20.Temperature }}"
    json_attributes:
      - DS18B20

history_graph:
  pool:
    name: Pool-Statistiken
    entities:
      - sensor.pool_temperatur
      - switch.pool
    hours_to_show: 168
    refresh: 60

group:
  pool:
    name: Pool
    control: hidden
    entities:
      - sensor.pool_temperatur
      - switch.pool

  pool_timer:
    control: hidden
    entities:
      - input_boolean.pool_timer_aktiv
      - input_datetime.pool_timer1_start
      - input_datetime.pool_timer1_stop
      - input_datetime.pool_timer2_start
      - input_datetime.pool_timer2_stop

input_boolean:
  pool_timer_aktiv:
    name: Timer aktiv
    initial: on
    icon: mdi:clock

input_datetime:
  pool_timer1_start:
    name: Timer 1 ein
    has_date: false
    has_time: true
    initial: '10:30'
    icon: mdi:clock-start
  pool_timer1_stop:
    name: Timer 1 aus
    has_date: false
    has_time: true
    initial: '14:00'
    icon: mdi:clock-end
  pool_timer2_start:
    name: Timer 2 ein
    has_date: false
    has_time: true
    initial: '16:00'
    icon: mdi:clock-start
  pool_timer2_stop:
    name: Timer 2 aus
    has_date: false
    has_time: true
    initial: '20:00'
    icon: mdi:clock-end

automation:
  - alias: pool_timer_start
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.pool_timer1_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.pool_timer2_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      condition: state
      entity_id: input_boolean.pool_timer_aktiv
      state: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.pool

  - alias: pool_timer_stop
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.pool_timer1_stop.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.pool_timer2_stop.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
      service: switch.turn_off
      entity_id: switch.pool
