switch:
  - platform: mqtt
    name: pool_filter_pump
    command_topic: cmnd/garden/pool/POWER
    state_topic: stat/garden/pool/RESULT
    value_template: '{{value_json.POWER}}'
    payload_off: 'OFF'
    payload_on: 'ON'
    availability_topic: tele/garden/pool/LWT
    payload_available: Online
    payload_not_available: Offline

sensor:
  - platform: mqtt
    name: pool_temp
    state_topic: "tele/garden/pool/SENSOR"
    unit_of_measurement: "째C"
    expire_after: 600
    value_template: "{{ value_json.DS18B20.Temperature }}"

binary_sensor:
  - platform: template
    sensors:
      pool_temp_too_high:
        value_template: >-
          {{ states("sensor.pool_temp")|float > states("input_number.pool_temp_threshold")|float }}

history_graph:
  pool:
    entities:
      - sensor.pool_temp
      - switch.pool_filter_pump
    hours_to_show: 168
    refresh: 60

input_boolean:
  pool_timer_aktiv:
    initial: on
    icon: mdi:clock

input_number:
  pool_temp_threshold:
    icon: mdi:oil-temperature
    #initial: 22
    min: 20.0
    max: 29.0
    step: 0.5
    unit_of_measurement: '째C'

input_datetime:
  pool_timer1_start:
    has_date: false
    has_time: true
    initial: '10:30'
  pool_timer1_stop:
    has_date: false
    has_time: true
    initial: '14:00'
  pool_timer2_start:
    has_date: false
    has_time: true
    initial: '16:00'
  pool_timer2_stop:
    has_date: false
    has_time: true
    initial: '20:00'

automation:
  - alias: cycle_pool_pump
    trigger:
      platform: state
      entity_id: binary_sensor.pool_temp_too_high
      to: 'on'
      for:
        minutes: 30
    condition:
      - condition: state
        entity_id: switch.pool_filter_pump
        state: 'off'
      - condition: time
        after: '06:00:00'
        before: '21:00:00'
    action:
      - service: notify.ios_iphone_von_dennis
        data_template:
          title: 'Pool'
          message: 'Die Temperatur im Pool betr채gt aktuell {{ states("sensor.pool_temp") }}째C, die Filterpumpe wird jetzt aktiviert'
      - service: switch.turn_on
        entity_id: switch.pool_filter_pump
      - delay:
          minutes: 15
      - service: switch.turn_off
        entity_id: switch.pool_filter_pump

  - alias: pool_timer_start
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.pool_timer1_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.pool_timer2_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      condition: state
      entity_id: input_boolean.pool_timer_aktiv
      state: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.pool_filter_pump

  - alias: pool_timer_stop
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.pool_timer1_stop.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.pool_timer2_stop.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
      service: switch.turn_off
      entity_id: switch.pool_filter_pump
