input_select:
  vacuum_room_select:
    name: Raum auswählen
    options:
      - Wohnzimmer
      - Küche
      - Flur
      - Bad
      - Toilette
      - Kinderzimmer

  vacuum_room_repeat:
    name: Anzahl der Reinigungsvorgänge
    options:
      - 1
      - 2
      - 3
    initial: 1
    icon: mdi:numeric

sensor:
  - platform: template
    sensors:
      roborock_s50_battery:
        friendly_name: 'Roborock S50 Batterie'
        value_template: "{{state_attr('vacuum.roborock_s50', 'battery_level')}}"
        unit_of_measurement: '%'
        device_class: battery

      roborock_s50_lifetime_cleaned_area:
        friendly_name: 'Gereinigte Fläche gesamt'
        value_template: "{{state_attr('vacuum.roborock_s50', 'total_cleaned_area')}}"
        unit_of_measurement: ㎡

      roborock_s50_lifetime_cleaning_time:
        friendly_name: 'Reinigungszeit gesamt'
        value_template: "{{(state_attr('vacuum.roborock_s50', 'total_cleaning_time') / 60)|round(1, 'floor')}}"

      roborock_s50_last_cleaned:
        friendly_name: 'Zeit seit letzter Reinigung'
        value_template: "{{relative_time(strptime(as_timestamp(state_attr('vacuum.roborock_s50', 'clean_stop'))|timestamp_custom('%Y-%m-%d %H:%M:%S%z'), '%Y-%m-%d %H:%M:%S%z'))}}"

      roborock_s50_lifetime_cleaning_count:
        friendly_name: 'Anzahl Reinigungen gesamt'
        value_template: "{{state_attr('vacuum.roborock_s50', 'cleaning_count')}}"

      roborock_s50_filter_remaining:
        friendly_name: '% Filter'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s50', 'filter_left') / 150) * 100) | round | int}}"

      roborock_s50_filter_hrs_remaining:
        friendly_name: 'Filter Stunden verbleibend'
        unit_of_measurement: 'h'
        value_template: "{{state_attr('vacuum.roborock_s50', 'filter_left')}}"

      roborock_s50_side_brush_remaining:
        friendly_name: '% Seitenbürste'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s50', 'side_brush_left') / 200) * 100) | round | int}}"

      roborock_s50_side_brush_hrs_remaining:
        friendly_name: 'Seitenbürste Stunden verbleibend'
        unit_of_measurement: 'h'
        value_template: "{{state_attr('vacuum.roborock_s50', 'side_brush_left')}}"

      roborock_s50_main_brush_remaining:
        friendly_name: '% Hauptbürste'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s50', 'main_brush_left') / 300) * 100) | round | int}}"

      roborock_s50_main_brush_hrs_remaining:
        friendly_name: 'Hauptbürste Stunden verbleibend'
        unit_of_measurement: 'h'
        value_template: "{{state_attr('vacuum.roborock_s50', 'main_brush_left')}}"

      roborock_s50_sensors_remaining:
        friendly_name: '% Sensoren'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s50', 'sensor_dirty_left') / 30) * 100) | round | int}}"

      roborock_s50_sensors_hrs_remaining:
        friendly_name: 'Sensoren Stunden verbleibend'
        unit_of_measurement: 'h'
        value_template: "{{state_attr('vacuum.roborock_s50', 'sensor_dirty_left')}}"
