input_select:
  vacuum_room_select:
    name: Choose a room to clean
    options:
      - Bathroom
      - Dining Room
      - Guest Bedroom
      - Hallway
      - Kitchen
      - Living Room

  vacuum_room_repeat:
    name: Number of times to clean the room
    options:
      - 1
      - 2
      - 3
    initial: 1
    icon: mdi:numeric

sensor:
  - platform: template
    sensors:
      roborock_s50_battery:
        friendly_name: 'Roborock S50 Battery'
        value_template: "{{state_attr('vacuum.roborock_s50', 'battery_level')}}"
        unit_of_measurement: '%'
        device_class: battery

      roborock_s50_lifetime_cleaned_area:
        friendly_name: 'Lifetime Cleaned Area'
        value_template: "{{state_attr('vacuum.roborock_s50', 'total_cleaned_area')}}"
        unit_of_measurement: ㎡

      roborock_s50_lifetime_cleaning_time:
        friendly_name: 'Lifetime Cleaning Time'
        value_template: "{{(state_attr('vacuum.roborock_s50', 'total_cleaning_time') / 60)|round(1, 'floor')}}"

      roborock_s50_last_cleaned:
        friendly_name: Relative time since last cleaning ended
        value_template: "{{relative_time(strptime(as_timestamp(state_attr('vacuum.roborock_s50', 'clean_stop'))|timestamp_custom('%Y-%m-%d %H:%M:%S%z'), '%Y-%m-%d %H:%M:%S%z'))}}"

      roborock_s50_lifetime_cleaning_count:
        friendly_name: 'Lifetime Cleaning Count'
        value_template: "{{state_attr('vacuum.roborock_s50', 'cleaning_count')}}"

      # Used for the Filter maintenance card
      roborock_s50_filter_remaining:
        friendly_name: '% Filter Remaining'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s50', 'filter_left') / 150) * 100) | round | int}}"

      # Used for the Filter maintenance card
      roborock_s50_filter_hrs_remaining:
        friendly_name: 'Filter Remaining Hours'
        unit_of_measurement: 'hrs'
        value_template: "{{state_attr('vacuum.roborock_s50', 'filter_left')}}"

      # Used for the Side Brush maintenance card
      roborock_s50_side_brush_remaining:
        friendly_name: '% Side Brush Remaining'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s50', 'side_brush_left') / 200) * 100) | round | int}}"

      # Used for the Side Brush maintenance card
      roborock_s50_side_brush_hrs_remaining:
        friendly_name: 'Side Brush Remaining Hours'
        unit_of_measurement: 'hrs'
        value_template: "{{state_attr('vacuum.roborock_s50', 'side_brush_left')}}"

      # Used for the Main Brush maintenance card
      roborock_s50_main_brush_remaining:
        friendly_name: '% Main Brush Remaining'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s50', 'main_brush_left') / 300) * 100) | round | int}}"

      # Used for the Main Brush maintenance card
      roborock_s50_main_brush_hrs_remaining:
        friendly_name: 'Main Brush Remaining Hours'
        unit_of_measurement: 'hrs'
        value_template: "{{state_attr('vacuum.roborock_s50', 'main_brush_left')}}"

      # Used for the Sensors maintenance card
      roborock_s50_sensors_remaining:
        friendly_name: '% Sensors Remaining'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s50', 'sensor_dirty_left') / 30) * 100) | round | int}}"

      # Used for the Sensors maintenance card
      roborock_s50_sensors_hrs_remaining:
        friendly_name: 'Sensors Remaining Hours'
        unit_of_measurement: 'hrs'
        value_template: "{{state_attr('vacuum.roborock_s50', 'sensor_dirty_left')}}"
