homeassistant:
  customize:
    sensor.nzbget_speed:
      friendly_name: Current NZBGet Speed
      icon: 'mdi:download'

input_boolean:
  motion_sensor_flur_aktiv:
    name: Bewegungsmelder Flur
    icon: mdi:radar
  motion_sensor_toilette_aktiv:
    name: Bewegungsmelder Toilette
    icon: mdi:radar
  motion_sensor_bad_aktiv:
    name: Bewegungsmelder Bad
    icon: mdi:radar
  motion_sensor_kueche_aktiv:
    name: Bewegungsmelder Küche
    icon: mdi:radar

group:
  settings_view:
    name: Einstellungen
    view: yes
    icon: mdi:settings
    entities:
      - group.home_assistant
      - group.network
      - group.bewegungsmelder
      - group.my_automations

  home_assistant:
    name: Home-Assistant
    entities:
      - input_boolean.git_auto_update
      - script.git_update_config
      - script.gw_add_device

  network:
    name: Netzwerk
    entities:
      - sensor.nzbget_download_paused
      - sensor.nzbget_speed
      - sensor.nzbget_queue_size

  bewegungsmelder:
    name: Bewegungsmelder
    entities:
      - input_boolean.motion_sensor_flur_aktiv
      - input_boolean.motion_sensor_kueche_aktiv
      - input_boolean.motion_sensor_bad_aktiv
      - input_boolean.motion_sensor_toilette_aktiv

